version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libsqlite3-dev
    - pkg-config
  tools:
    python: "3.12"
    rust: "latest"
  commands:
    # Install build dependencies
    - pip install -r docs/requirements.txt
    - pip install maturin
    # Build the rapsqlite package (Rust is available via tools.rust)
    - echo "Building rapsqlite package with maturin..."
    - |
      maturin build --release || (echo "Maturin build failed!" && exit 1)
    # Verify the wheel was built
    - echo "Checking for built wheels..."
    - |
      ls -la target/wheels/ || (echo "ERROR: No wheels found in target/wheels/" && exit 1)
    # Install the built wheel
    - echo "Installing rapsqlite wheel..."
    - |
      pip install target/wheels/rapsqlite-*.whl --force-reinstall || (echo "ERROR: Failed to install wheel" && exit 1)
    # Verify rapsqlite can be imported (from installed package, not source)
    - echo "Verifying rapsqlite import..."
    - |
      cd /tmp && python << 'PYEOF'
      import sys
      import os
      # Remove source directory from path to ensure we import from installed package
      default_path = "/home/docs/checkouts/readthedocs.org/user_builds/rapsqlite/checkouts/latest"
      source_dir = os.environ.get("READTHEDOCS_PROJECT_DIR", default_path)
      if source_dir in sys.path:
          sys.path.remove(source_dir)
      import rapsqlite
      print("Successfully imported rapsqlite", rapsqlite.__version__)
      PYEOF
    - |
      if [ $? -ne 0 ]; then
        echo "ERROR: Failed to import rapsqlite"
        exit 1
      fi
    # Build documentation
    - echo "Building documentation with Sphinx..."
    - |
      sphinx-build -b html docs/ docs/_build/html || (echo "ERROR: Sphinx build failed" && exit 1)

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
