version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/ docs/_build/html

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
