version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: "stable"
  commands:
    # Install build dependencies
    - pip install -r docs/requirements.txt
    - pip install maturin
    # Build the rapsqlite package (Rust is available via tools.rust)
    - maturin build --release
    # Install the built wheel
    - pip install target/wheels/rapsqlite-*.whl --force-reinstall
    # Build documentation
    - sphinx-build -b html docs/ docs/_build/html

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
