version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - libsqlite3-dev
    - pkg-config
  tools:
    python: "3.12"
    rust: "stable"
  commands:
    # Install build dependencies
    - pip install -r docs/requirements.txt
    - pip install maturin
    # Build the rapsqlite package (Rust is available via tools.rust)
    - maturin build --release
    # Verify the wheel was built
    - ls -la target/wheels/ || echo "Warning: No wheels found in target/wheels/"
    # Install the built wheel
    - pip install target/wheels/rapsqlite-*.whl --force-reinstall
    # Verify rapsqlite can be imported
    - python -c "import rapsqlite; print(f'Successfully imported rapsqlite {rapsqlite.__version__}')" || echo "Warning: Failed to import rapsqlite"
    # Build documentation
    - sphinx-build -b html docs/ docs/_build/html

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
