"""Type stubs for _rapsqlite Rust extension module."""

from typing import Coroutine, Any, List

class Connection:
    def __init__(self, path: str) -> None: ...
    def execute(self, query: str) -> Coroutine[Any, Any, None]: ...
    def fetch_all(self, query: str) -> Coroutine[Any, Any, List[List[str]]]: ...
